from graph2 import Graph

g = Graph(20)
g.visualize()
print(g)
print(g.edge_list)
print("encrypt g2")
g.encrypt_g2()
g.visualize()
print(g.edge_list)
print(g.vertex_list)
print(g.keys)
print("encrypt g3")
g.encrypt_g3()
g.visualize()
print(g.edge_list)
print(g.vertex_list)
print(g.keys)
print("decrypt")
print(g.find_weight(0, 1))
g.decrypt()
g.visualize()
print(g.edge_list)
print(g.vertex_list)